### ISSUE TITLE
Option to disable nestia in tests [$$$]

### ISSUE THREAD

**Issue by rivatove** [samchon/nestia#1007]
## Feature Request

I can contribute financially to implement this feature request.

  - A description of the problem you're trying to solve.
  
My Jest tests finish fairly quickly when using `ts-jest` with the `isolatedModules` flag enabled. However, nestia won't work with that flag because (I assume) it looks for type information which isn't there.

It raises the following error:
`TypeError: Cannot read properties of undefined (reading '0')`
  
When I disable the `isolatedModules` flag, my tests pass but their execution time becomes way too high. It increases almost ten-fold.
  
  - An overview of the suggested solution.
  
I would like to be able to run my Jest tests with the `isolatedModules` flag enabled. To achieve that, I need to be able to disable nestia run-time validation. I can do that by using a dedicated tsconfig file without the `plugins` parameter. Obviously, it makes nestia complain that `no transform has been configured.`

If nestia accepted an explicit `null` driver or something of that kind, I would be able to run my tests with the mentioned flag. The obvious drawback is that the run-time validation would be gone. But that's not something I want to test so that doesn't concern me.

I really appreciate nestia. As mentioned, I can contribute financially if this feature request is honored and consequently, I'm able to use the library in my project.

**Comment by samchon** [comment]
```typescript
import { NoTransformConfigureError } from "@nestia/core/lib/decorators/NoTransformConfigureError";

NoTransformConfigureError.throws = false;
```

There is an option turning off transformation error in the runtime, but it had been desinged only for SDK generation.

If you want, it is possible to make your `jest` working by enhancing the `NoTransformConfigureError.throws` related logic. However, it not recommended for test purposes, because the runtime validation like request body data, it is essential feature in the test program.

Instead, I recommend `@nestia/e2e` solution. Also, even in the `ts-jest`, you can avoid the long-time waiting problem just by pre-compiling the test program like `tsc --watch --project tsconfig.test.json` command.

- https://nestia.io/docs/e2e/why/

**Comment by rivatove** [comment]
I couldn't get it working using the above workaround. If I remember correctly, marking the `NoTransformConfigureError.throws` as false makes the decorator return undefined, which is not a valid decorator function and throws at runtime.

What I ended up doing was adding this code to the `jest.setup.ts` file.

```ts
import { Param } from '@nestjs/common';

jest.mock('@nestia/core', () => ({
  TypedParam: Param,
}));
```

**Comment by rivatove** [comment]
Hi @samchon,

I've been trying to use the `tsc --watch` workaround you mentioned. It doesn't seem to have an effect though; the first test run is always of the same speed. Subsequent test runs are always faster (assuming no code changes) but that isn't very helpful.

Do you have an idea what I could be doing wrong?
