### ISSUE TITLE
Invalid error: `@nestia/sdk @nestia/sdk has not been installed.`

### ISSUE THREAD

**Issue by pivee** [samchon/nestia#362]
## Bug Report

Running `npx nestia swagger` even after `npx nestia setup` results in the following error.

```sh
@nestia/sdk has not been installed. Run "npx nestia setup" before.
```

### Logs

```sh
pivee@den : ~/projects/sandbox/nestia-test-npm
[0] % nest new .  
⚡  We will scaffold your app in a few seconds..

? Which package manager would you ❤️  to use? npm
CREATE .eslintrc.js (663 bytes)
CREATE .prettierrc (51 bytes)
CREATE README.md (3340 bytes)
CREATE nest-cli.json (171 bytes)
CREATE package.json (1946 bytes)
CREATE tsconfig.build.json (97 bytes)
CREATE tsconfig.json (546 bytes)
CREATE src/app.controller.spec.ts (617 bytes)
CREATE src/app.controller.ts (274 bytes)
CREATE src/app.module.ts (249 bytes)
CREATE src/app.service.ts (142 bytes)
CREATE src/main.ts (208 bytes)
CREATE test/app.e2e-spec.ts (630 bytes)
CREATE test/jest-e2e.json (183 bytes)

✔ Installation in progress... ☕

🚀  Successfully created a new project
👉  Get started with the following commands:

$ cd .
$ npm run start

                                         
                          Thanks for installing Nest 🙏
                 Please consider donating to our open collective
                        to help us maintain this package.
                                         
                                         
               🍷  Donate: https://opencollective.com/nest
                                         

pivee@den ‹ main ● › : ~/projects/sandbox/nestia-test-npm
[0] % npm i -g nestia@next      

changed 60 packages in 7s

16 packages are looking for funding
  run `npm fund` for details

pivee@den ‹ main › : ~/projects/sandbox/nestia-test-npm
[0] % npx nestia setup       
----------------------------------------
 Nestia Setup Wizard
----------------------------------------
? Package Manager npm
? TS Config File tsconfig.json

npm install --save-dev ts-patch@latest
npm install --save-dev ts-node@latest
npm install --save-dev typescript@4.9.5
npm run prepare
npm install --save typia@latest
npm install --save @nestia/core@latest
npm install --save-dev @nestia/sdk@latest

pivee@den ‹ main ● › : ~/projects/sandbox/nestia-test-npm
[0] % npx nestia swagger
@nestia/sdk has not been installed. Run "npx nestia setup" before.
```

### Minimal reproduction repository

```bash
git clone https://github.com/pivee/nestia-test-npm
cd nestia-test-npm
npx nestia sdk
```

**Comment by kakasoo** [comment]
Hi. I'm not the owner of this repository, but I've tried running the script you gave me. The only part I changed is `npx nestia sdk --out src/apis`. Because there was no `nestia.config.ts` in your project.
I successfully created an SDK in the src/apis path. (This case uses npm) In my opinion, are you managing the project using yarn? If that's the case, you might have a problem because you're using cache. Because I had the same problem when configuring the repository with yarn. I hope this case will help you.

**Comment by kakasoo** [comment]
```bash
git clone https://github.com/pivee/nestia-test-npm
cd nestia-test-npm
npx nestia sdk --out src/apis
```

Hi. I'm not the owner of this repository, but I've tried running the script you gave. The only part I changed is `npx nestia sdk --out src/apis`. Because there was no `nestia.config.ts` in your project.
I successfully created an SDK in the src/apis path. In my opinion, are you managing the project using yarn? If that's the case, you might have a problem because you're using cache.

**Comment by pivee** [comment]
Hi @kakasoo! Thanks very much for you response.

I'm not using `yarn` -- rather `npm` and `pnpm` on a separate repo.

I've tried adding in `nestia.config.ts`, but I end up with the same error. I've pushed that to the reproduction repo.

I tried `npx nestia sdk --out src/apis` too. However, there's no change. I'm getting the same error.

```sh
pivee@den ‹ main › : ~/projects/sandbox/nestia-test-npm
[255] % npx nestia sdk --out src/apis
@nestia/sdk has not been installed. Run "npx nestia setup" before.
```

**Comment by kakasoo** [comment]
```typescript
import { INestiaConfig } from '@nestia/sdk';

const config: INestiaConfig = {
  input: 'src/modules',
  output: 'src/apis', // There is no output for SDK in your nestia.config.ts.
  swagger: { ... },
};
export default config;

```
@pivee 
Apart from this issue, your `nestia.config.ts` is missing `output` property. By the way I pull your repository and create sdk and it will run normally. There is no problem when I use your repository as it is. I can't help because I can't reproduce this problem. There is no difference between the two of us except that the package manager is different. So it's all I can do to guess that there's a problem with the package manager.

**Comment by kakasoo** [comment]
Oh, I recreated this problem. I'll experiment with it. Please wait a moment.

**Comment by kakasoo** [comment]
@pivee 

```bash
npm install --save-dev nestia
npx nestia swagger
npx nestia sdk
```

Install dev-dependency in your project repository, and then tell me result plz.

**Comment by pivee** [comment]
Thanks @kakasoo! 🙏🏻 Installing `nestia` as a devDependency worked for me.

I had installed it as a global package earlier using `npm install -g nestia`.
