### ISSUE TITLE
Separate TypedRoute's TypeGuardError from TypeGuardError raised by application code

### ISSUE THREAD

**Issue by cstria0106** [samchon/nestia#489]
## Feature Request
Thanks for your suggestion. Feel free to just state your idea. Writing the issue, it would better to filling the below items:

  ### A description of the problem you're trying to solve.
I can't separate a TypedRoute's TypeGuardError from a TypeGuardError raised by a typia in my code, which complicates error handling.

  ### An overview of the suggested solution.
Separate TypedRoute's TypeGuardError from TypeGuardError raised by application code.

### Code examples showing the expected behavior.
```ts
class TypedRouteValidationError extends HttpException {
    ...
}

@TypedRoute.Post('api')
async create(@TypedBody() body: MyBody) { // throws TypedRouteValidationError on invalid user input
    typia.assertEquals(body, NotMyBody); // throws typia's original TypeGuardError
}
```

**Comment by samchon** [comment]
`TypedBody()` throws 400 `BadRequestException` error.

So, you don't need to worry about it this issue.

**Comment by cstria0106** [comment]
Yes, we can receive a 400 Bad Request error with TypedBody. The issue I'm facing is that TypeGuardError thrown within the logic (such as controller body or service), rather than in the validation part of the route, is also automatically replaced with a 400 Bad Request error. I believe that users should receive a 500 Internal Server Error for TypeGuardErrors that occur internally.

**Comment by samchon** [comment]
Upgrade to `@nestia/core@1.6.3`, then it would work as you wish.

Thanks for reporting.

**Comment by cstria0106** [comment]
Thank you. But we might still need a way to handle TypeGuardErrors that happen in the validation logic of TypedRoute separately. If it doesn't make things more complicated, please consider adding new error types for validation within TypedRoute/Body.

**Comment by samchon** [comment]
Can you explain why the error class should be separated?

**Comment by cstria0106** [comment]
Oh, I'm sorry.
I just tested it with the new project, and I confirmed that it's functioning as desired (giving a 400 error for invalid input and a 500 error for TypeGuardErrors within the app).
Thank you so much for resolving this.

**Comment by rojiwon123** [comment]
> Can you explain why the error class should be separated?

i think, using sparated error class is more compatible.

Many project  cannot always keep all libraries up to date. When using a specific version of NestJS with Nestia, there are cases where HttpExceptions propagated by Nestia's decorators cannot be caught by NestJS filters.

The reason is explained here: https://github.com/samchon/nestia/issues/353#issuecomment-1560665567

In such scenarios, to enable developers to handle errors smoothly, it is necessary for Nestia to define and export an independent exception class. As a result, developers can directly write catch code for it in their projects.

example version
"@nestjs/core": "8.2.6"
"@nestjs/common": "8.2.6"
"@nestia/core": "2.4.3"

in this case, nestjs `HttpException` filter can't catch error from nestia decorator.
