### ISSUE TITLE
Allow developer to customize response structure

### ISSUE THREAD

**Issue by HenryWu01** [samchon/nestia#541]
## Question
I want to achieve a response strcture like this:
```
{
    "code": 200,
    "message: "ok",
    "data: {
        "vip": 333,
        "enterprise": 14,
        "pension": 712
    }
}
```

Adding a global interceptor is not possible since when the respons hit interceptor, it has already been process by nestia's internal ``TypedRouteInterceptor``:
```TypeScript
class TypedRouteInterceptor implements NestInterceptor {
    public constructor(private readonly stringify: (input: any) => string) {}

    public intercept(context: ExecutionContext, next: CallHandler) {
        const http: HttpArgumentsHost = context.switchToHttp();
        const response: express.Response = http.getResponse();
        response.header("Content-Type", "application/json");

        return next.handle().pipe(
            map((value) => this.stringify(value)),
            catchError((err) => route_error(http.getRequest(), err)),
        );
    }
}
```

If using a global interceptor, the response will become something like this:
```
{
    "code": 200,
    "message": "ok",
    "data": "{\"vip\":333,\"enterprise\":14,\"pension\":712}"}
```

I'm thinking of some thing like allowing user to pass a param to wrap the value? Like the planned TypeException?

By the way, ``express.Response`` in the above code should be changed to ``express.Response | FastifyReply``?

**Comment by samchon** [comment]
https://typia.io/playground/?script=JYWwDg9gTgLgBDAnmYBDOAzKERwERIqp4DcAUGcAHYwCmUGqAxrXAJICytIARvXAG8ycEXAD0AKglxhouNIACGaCFTwAruuAATGXPli9onQC44AZxhRqAc3KyRk6Q5GLlUVfG6pgAGyOiEoYu3n5mltZUdhRyTi7ycAqErFo08Yog1KDquABMAAzpibQAHky+6ubAAG60HKgl2bgAjPmF+kEuqDa0ZlQ5fFDkcmCoULQ0Zpzcg3AAPnD9vr7DokwAFn7a41RTXLz0ANoAuuQAvhSEaAB0TONqtADKVrbAGIgAPNMHUAB8ABQAShIQA

`@TypedRoute.Get()` utilizes `typia.stringify<T>()` function, and the `typia.stringify<T>()` function ignores every extra properties that are not listed in the target type `T`. Therefore, even though I provide custom global interceptor way, it would not mean anything because of such characteristic of `typia.stringify<T>()` function.

Thus, if you want to customize response data through global interceptor, just use `@Get()` function of `@nestjs/common`.

Otherwise you want to keep using `@TypedRoute.Get()` function, make an utility function and call it as below.

```typescript
export function wrap<T>(input: T): IResponse<T>;

export class SomeClass {
    public someMethod(): IResponse<T> {
        const data: T = {...};
        return wrap(data);
    }
}
```
